#!/bin/bash
# Initializes hosts, copying SSH keys

function init_host {
	echo ==== $1
	ssh-keygen -f "$HOME/.ssh/known_hosts" -R $1
	ssh-copy-id -i ~/.ssh/dsidorenko.pub $1
}
# d s e n l
# 
for ENV in d c s n l q
do
	for APP in kadabra abra gamayun krabby numel psyduck simurgh swinub zubat watchdog
	do
		init_host app$APP.$ENV.dev.agent.ru
	done

	for APP in nginx amq1
	do
		FULL_HOST_NAME=$APP.$ENV.dev.agent.ru
		init_host $APP.$ENV.dev.agent.ru
	done
done
