#!/bin/bash
# Infects given host with personalized settings.
# infect with no arguments infects all hosts in .ssh/known_hosts.

if [[ "$1" != "" ]]; then
	hosts="$1"
else
	hosts=$(./known_hosts | grep -v 'vs-as')
fi

SCRIPT=$(cat virus)

for host in $hosts
do
	echo "== infecting $host"
	ssh $host "$SCRIPT"
done
