#!/bin/bash
# Initializes hosts, copying SSH keys

function init_host {
	echo ==== $1
	ssh-keygen -f "/home/dsidorenko/.ssh/known_hosts" -R $1
	ssh-copy-id $1 -i ~/.ssh/dsidorenko.pub
}

for ENV in d s e
do
	for APP in abra gamayun krabby numel psyduck simurgh swinub watchdog yandexws zubat
	do
		init_host app$APP.$ENV.dev.agent.ru
	done

	for APP in nginx amq1
	do
		FULL_HOST_NAME=$APP.$ENV.dev.agent.ru
		init_host $APP.$ENV.dev.agent.ru
	done
done
