#!/bin/bash
# Force update of SSH fingerprints

if [[ "$1" != "all" ]]; then
	hosts="$1"
else
	hosts=$(./known_hosts | grep -v 'vs-as')
fi

for host in $hosts
do
	echo ==== $host
	ssh-keygen -f "$HOME/.ssh/known_hosts" -R $host
	ssh $host 'hostname'
done
